### ISSUE TITLE
Aerell

### ISSUE THREAD

**Issue by Wilke000** [hackthegamezjj/Blooket-Hacks#10]
U stole his code. Please close. Not sure what happened to Aerell (Minescraft2) but yea. U STOLE HIS CODE

**Comment by hackthegamezjj** [comment]
Im one of his friends. I asked if I could help him and he agreed

**Comment by hackthegamezjj** [comment]
thanks

**Comment by Thing3487** [comment]
> thanks

Fake, he’s planning with me on discord on how to  take you down
