### ISSUE TITLE
Hello, I’m Thing3487

### ISSUE THREAD

**Issue by Thing3487** [hackthegamezjj/Blooket-Hacks#9]
![3CE61C89-D1CA-41DC-A8E3-D5A52A14EAE9](https://user-images.githubusercontent.com/126958686/227717234-9893391f-0d96-4fbc-bbc5-4333d077c9a8.jpeg)
https://github.com/hackthegamezjj/Blooket-Hacks/issues/7

**Comment by Thing3487** [comment]
@hackthegamezjj

**Comment by hackthegamezjj** [comment]
The FUCK?
